### PR TITLE
Add docker dotenv vars

### LINKED ISSUE #70: Dockerize the application
Develop a Docker solution that would allow us to run the entire application stack either locally on a developer's machine or on production servers.

Ideally we would want separate Docker containers for each part of the stack:
* web/application server(s)
* background workers (sidekiq, imagemagick, soffice, ffmpeg, etc.)
* redis
* solr
* fedora
* database (for running locally.  Would likely use external DB in production)
~~* IIIF server (e.g. Cantaloupe, Loris, etc.)~~ *breakout into seperate issue*

Resources:
* Treatment DB: https://github.com/uclibs/treatment_database/pull/87/files & https://github.com/uclibs/treatment_database/pull/95/files

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #70 

Add .dotenv file with variables for dev-mode docker build. Updated [hyrax-docker](https://github.com/uclibs/hyrax-docker/pull/30) submodule with directive to copy docker dotenv at build time.

### CODE REVIEW

**Comment by hortongn** [comment]
@crowesn What are the steps I should follow to spin this up so I can test it?

**Comment by crowesn** [comment]
@hortongn I'll add more to the readme;

1. `cd` to hyrax-docker directory
1. `docker-compose up -d --build`

**Comment by crowesn** [comment]
hm
Screen Shot 2020-09-02 at 3 48 47 PM

**Comment by crowesn** [comment]
@hortongn Ideas about this? 
```
bash-4.2# /opt/fits/fits.sh -i /tmp/uploads/hyrax/uploaded_file/file/1/seanCrowe_portrait_03.jpg 
Sep 03, 2020 2:26:12 PM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolCLIException: Error calling external command line routine (Cannot run program "file": error=2, No such file or directory)
	at edu.harvard.hul.ois.fits.tools.utils.CommandLine.exec(CommandLine.java:47)
	at edu.harvard.hul.ois.fits.tools.fileutility.FileUtility.<init>(FileUtility.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:136)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:72)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:239)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:121)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:110)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:290)
```

**Comment by hortongn** [comment]
@crowesn What version of Fits are you using?  I know there are "good" versions of Fits that work well with Samvera.  See https://github.com/samvera/hyrax#prerequisites

**Comment by crowesn** [comment]
> @crowesn What version of Fits are you using? I know there are "good" versions of Fits that work well with Samvera. See https://github.com/samvera/hyrax#prerequisites

1.0.5

**Comment by hortongn** [comment]
@crowesn So far I've been able to reproduce your `Cannot run program "file"` error, but have not beed able to figure it out.

**Review by hortongn — APPROVED** [review]
@crowesn 👍  Works great.  merging

**Comment by hortongn** [comment]
Also, user and work data was preserved even after I deleted the containers and did a fresh build.  So it must be using an external location to store the content.

**Pull request merged**
