### PR TITLE
Add nginx server

### LINKED ISSUE #106: Use Nginx web server in production environments
Create an Nginx web server container that accepts requests on port 80 and forwards them to the application server (running on it's current port).

Statics assets (assets|images|javascripts|stylesheets|swfs|system) should be served by the web server.

See the implementation in the the treatment_database as an example:
https://github.com/uclibs/treatment_database/commit/a9219327313891395ace814585543fcb2bd3e659

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #106 

Setup container for nginx. 

Changes proposed in this pull request:
* New container for nginx with config
* tweak ports in docker-compose
* note that this changes container names so it will probably require a manual rebuild on curly

### CODE REVIEW

**Comment by hortongn** [comment]
@crowesn #108 is merged and this can be rebased.

**Comment by hortongn** [comment]
@crowesn While reviewing this PR I may be hitting the solr problem you resolved in https://github.com/uclibs/uc_drc/pull/116.  Can you rebase this branch and I'll re-review?  There's also a file conflict with docker/web/scripts/docker-entrypoint.sh

**Comment by crowesn** [comment]
@hortongn done

**Review by hortongn — APPROVED** [review]
@crowesn Works well in both development and production modes. 👍

**Pull request merged**
