### PR TITLE
Configure docker to run on curly / sandbox

### LINKED ISSUE #74: Standup application in sandbox
Depends on: https://github.com/uclibs/uc_drc/issues/73

Let's get the application as it is right now running on curly.libraries.uc.edu.  It will be good to have a place to try the application or push up a branch for people to test when needed.

We will want Fedora and Solr content to persist between restarts

To make deploys easier, we should use capistrano (https://github.com/uclibs/uc_drc/issues/73)

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #74 

Changes proposed in this pull request:
* Move docker config to app root directory
* De-commission hyrax-docker submodule
* Update docker-compile.yml to run both on local and curly.libraries.uc.edu
* Add dot-env variables for curly.libraries.uc.edu
* Update readme

### CODE REVIEW

**Comment by crowesn** [comment]
@hortongn @scherztc 

This should be ready to go - I'd like to get this merged before the bulkrax/Alison flex if possible, so that we can use docker to stage those branches.

**Comment by crowesn** [comment]
This is running on http://curly.libraries.uc.edu:3010.

**Review by hortongn — COMMENTED** [review]
@crowesn Can you explain to me why we need copies of solr config files in docker/solr/config in addition to what we already have in solr/config?  Can we instead copy the contents of solr/config/ to docker/solr/config/ when we build?  We can chat if it's easier to explain in person.

**Comment by crowesn** [comment]
Yes I think we can do that - would you like that in this PR or shall I open another issue?

**Comment by hortongn** [comment]
I'll finish reviewing the PR and will let you know.  We can probably make the solr/config thing a new issue, but let me see if other changes are needed.

**Review by hortongn — APPROVED** [review]
@crowesn This is excellent.  You can merge this unless @scherztc wants to review it too.  Please make a separate issue for the docker/solr/config thing.

**Comment by hortongn** [comment]
@crowesn Oh yeah, 2 things about the README (these can be a separate PR if you want):
1. I had to use `docker logs` not `docker log` to view a container's log
2. Is there a way to run the specs using docker? If so, we should add that command to the README.  We might be able to simplify our CI config if specs can all be run in docker.

**Comment by crowesn** [comment]
1.  I’ll update the docker logs typo.
  2.  It’s not currently setup to run specs but it can be. I’ll open an issue for this.

**Pull request merged**
