### PR TITLE
call positive? on count

### LINKED ISSUE #122: metadata rake task check for existing profile
Error in rake task on curly using `positve?` method to check for existing metadata profiles.

```
rake aborted!
NoMethodError: undefined method `positive?' for #<Class:0x000000000d961858>
/opt/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/opt/hyrax/lib/tasks/metadata_profile.rake:6:in `block (2 levels) in <main>'
/opt/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/opt/rh/rh-ruby27/root/usr/local/bin/bundle:23:in `load'
/opt/rh/rh-ruby27/root/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => metadata_profile:load_default
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #122 

Make sure to call `positive?` on `count` and not the base profile class

### CODE REVIEW

**Comment by crowesn** [comment]
@hortongn please review, this should fix curly.

**Comment by hortongn** [comment]
@crowesn This seems to fix the problem with the app not starting, but introduces a new problem.  When I try to create a work on curly or locally using this branch I get the error below.  When I look at the metadata profiles it does list 1.0.beta2.

error

**Comment by crowesn** [comment]
I took a look and I think somehow the hyrax default (generic work) metadata profile was loaded. I'm going to do some testing and see if I can clean things up.

**Comment by hortongn** [comment]
Still getting the same error when creating a work.  I verified I have the newer lib/tasks/metadata_profile.rake

**Review by hortongn — APPROVED** [review]
After deleting volumes things now continue to work after I rebuild.  Merging

**Pull request merged**
